### ISSUE TITLE
Commands defined in yargs(such as TypeORM) fail after adding ConsoleModule

### ISSUE THREAD

**Issue by MichaelHindley** [Pop-Code/nestjs-console#126]
Following the instructions in readme,
when adding ConsoleModule to the main application module,
then all TypeORM commands start failing with "command not found".
Removing the ConsoleModule from the main application module restores TypeORM functionality.

Latest as of today versions of everything.

**Comment by Rmannn** [comment]
Be sure to have commander 4.1.1 and not v5.0.0
Commander has published a new major version and the console module os not yet ready for it.

**Comment by MichaelHindley** [comment]
This was indeed the case! tyvm

**Comment by MichaelHindley** [comment]
I may have been a bit fast, turns out I was standing in a branch where the console was not added. This behaviour is observed on commander@4.1.1 as well.

I have setup a repo here:
https://github.com/MichaelHindley/nestjs-console-repro

Run `npm i && npm build` to setup.
Then, running `npm run typeorm schema:sync` results in: 
````
"schema:sync" command not found
```

removing the `ConsoleModule` from `app.module.ts` fixes it.

**Comment by Rmannn** [comment]
Thanks for the repo, let me have a look and come back to you.

**Comment by Rmannn** [comment]
After clone, i had to add the import of the ConsoleModule in the AppModule. 
It was not present.

Then i ran the command to be sure the console was working

```sh 
ts-node -r tsconfig-paths/register src/console.ts "--help"
```

As expected the result was
```sh
Usage: console.ts [options] [command]

Options:
  -h, --help        output usage information

Commands:
  list <directory>  List content of a directory
````

Then i ran the typeorm command you gave me (after installing and starting a postgres sql server)
I had to remove the debugger flag (--inspect-brk) cause i do not have a debugger ready.

```sh
npm run typeorm schema:sync
```

The result was
```sh
query: START TRANSACTION
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'typeorm_metadata'
query: COMMIT
Schema syncronization finished successfully.
```

Everything worked well.
I am sorry, I was not able to reproduce the bug.

**Comment by MichaelHindley** [comment]
(I pushed the changes missing in the repro)

Super interesting, my output for `ts-node -r tsconfig-paths/register src/console.ts "--help"`is the same as yours, but here is my output for `npm run typeorm schema:sync`

![image](https://user-images.githubusercontent.com/1016639/79684185-b03bbc00-822f-11ea-96f3-c238883c78d4.png)

Removing ConsoleModule gives me the same output for `npm run typeorm schema:sync` as you.

By stepping through the call stack, I notice the error is due to the `this.listeners` array does not contain the `schema:sync` command in `node_modules/commander/index.js:891`. It then throws an error which goes to the catch block in console.ts and the process rightfully exits.

If I remove the ConsoleModule, the commander breakpoints are not even hit, this is because typeorm uses the `yargs` package for defining commands and not Commander.

If I remove the `process.exit(1)` line, I still get the error from Commander that the command is not found, but then it goes to `yargs` and runs the command successfully, since it does exist in that context.

Does nestjs-console check/lift/sync `yargs` based commands as well? It seems to hijack the entrypoint for all commands and not only Commander based commands.

I do wonder how come in your case, the error is not thrown, since the code path would result in an empty `this.listeners` in Commander no matter how I look at it, and thus throw an error which would lead to the `process.exit(1)` block every time. Could you perhaps print the members of your `this.listeners` array out?

node: 12.9.1
os: MacOS Catalina 0.15.4

**Comment by Rmannn** [comment]
I tried by syncing the node version. No luck, no bug.

> By stepping through the call stack, I notice the error is due to the this.listeners array does not contain the schema:sync command in node_modules/commander/index.js:891. It then throws an error which goes to the catch block in console.ts and the process rightfully exits.

The this.listeners can not contain the `schema:sync` command. This command is not registered on commander and had nothing to do with it. Only the entry point cli.js (from typeorm) can understand `schema:sync` command.

> Does nestjs-console check/lift/sync yargs based commands as well? It seems to hijack the entrypoint for all commands and not only Commander based commands.

nestjs-console should not be invoked when you call the typeorm command. It is initialized and working only if you use the console.ts/js file as entry point. The init and boot are done in this file only.

>  I do wonder how come in your case, the error is not thrown

The code in the console.ts/js should never be invoked when you call the typeorm module.

So the first thing to check is WHY the stack contains code from the nestjs-console module when you call the cli of typeorm.
Is really the nestjs-console module that is throwing the error ? If yes, why ? It shouldn't be in the stack. 
it's a different context, like a different application.

Maybe you can try to investigate here, this is the only place where the console module is throwing a `command not found` error.
https://github.com/Pop-Code/nestjs-console/blob/ff2d4a302ff8a9f0a713fa44c22fdd85d6e8abdd/src/service.ts#L226-L230

Maybe you have a global node module that is interacting on your computer ?
Could you try on a fresh node install ?

thx.

**Comment by MichaelHindley** [comment]
I can confirm that the code in `console.ts` was executed because of typeORM doing a `require` call to all files matching the glob for `entities` in `ormconfig.json`, in this particular case it was adding all `.js` files in the `dist` directory, where `console.js` was as a result of `npm run build`.

The require call was then executing the inline bootstrap code.

So that was the root cause! :)

**Comment by Rmannn** [comment]
Nice catch !  I was testing using sources, this is why the bug was not present. The dist folder is not existing on my side.
