### ISSUE TITLE
Redundant usage instructions printed on every command

### ISSUE THREAD

**Issue by MichaelHindley** [Pop-Code/nestjs-console#127]
When following readme and creating a @Command class,
then running any command within a NestJS context, including default commands and the @command,
results in redundant spam about usage every time, even when starting the application:

```
Usage: main [options] [command]

Options:
  -h, --help             display help for command

Commands:
  example-command  		 Example
  help [command]         display help for command
```

![image](https://user-images.githubusercontent.com/1016639/79066130-a822d000-7cb5-11ea-8777-a1c849510114.png)

**Comment by Rmannn** [comment]
Is your command async ? 
Is your command returning a Promise?
This is required to work with async command. 
When an async command is executed, the console module will wait for a promise to resolve. If you start a server instance inside a command, you should return a promise that will resolve when the server exit and throw on server error. 

Also be sure to exit the process in the bootstrap after the execution of the promise. If the node process is not explicitly exited, commander package will continue the execution of his code flow and display some defaults.

**Comment by Rmannn** [comment]
last thing, are you using commander v5? 
the version of the console module is not yet compatible with v5.
The repo has a commander v5 branch that is up to date with the last version of commander. But not published on npm. It will be soon.
So if you re using commander v5, simply downgrade to 4.1.1.

**Comment by MichaelHindley** [comment]
Yep, this was the case! The readme specifies to install the latest version, so you get 5 :)
