### ISSUE TITLE
A command with multiple arguments is not working

### ISSUE THREAD

**Issue by JoRoPi** [Pop-Code/nestjs-console#148]
I think the actual implementation: https://github.com/Pop-Code/nestjs-console/blob/305c81d41e040e97f9de88420e8c138123c55340/src/service.ts#L138-L149 made this command fail, you get only first argument :
```
    cs.createCommand(
      {
        command: 'historicoContrato <cod-contrato> <archivo>',
        description: 'Exportación de las anotaciones en el histórico referentes al contrato especificado',
      },
      this.exportaCSVHistoricoContrato,
      gcExportaCSV,
    );

```

**Comment by Rmannn** [comment]
Thx for this PR, I will check it Asap.

**Comment by JoRoPi** [comment]
Fine fix.

**Comment by MaSpeng** [comment]
How about a merge and release of this fix? 😄

**Comment by Rmannn** [comment]
I will do it this week, sorry, I had no time to merge it until now

**Comment by jdgriffith** [comment]
Any chance this will get merged soon?

**Comment by Rmannn** [comment]
Yes tomorrow (france), review and update are currently in progress.

**Comment by jdgriffith** [comment]
Thanks! Great package btw.
