### ISSUE TITLE
Last version not work with example

### ISSUE THREAD

**Issue by jrsanchezalcala** [Pop-Code/nestjs-console#155]
Last version throw (node:11492) UnhandledPromiseRejectionWarning: TypeError: parent.addCommand is not a function

When i downgrade to version 2.1.0 everything works welll

**Comment by Rmannn** [comment]
It seems the readme is up to date with latest version. Maybe I am wrong, if yes can you show me wich examples? addCommand method does not exists anymore.
you can use
service.createCommand()
or
service.createGroupCommand()
Note that with version > 3.0.0 you have to upgrade to commander >= 5.1.0

**Comment by Sairyss** [comment]
Same here, created console module exactly like in the example but it throws an error: 

`TypeError: parent.addCommand is not a function
    at ConsoleService.createCommand (D:\My\Code\notifications-service\node_modules\nestjs-console\src\service.ts:167:16)
    at scanResponse.forEach (D:\My\Code\notifications-service\node_modules\nestjs-console\src\module.ts:34:30)`

Downgrading to 2.1.0 fixed the issue

**Comment by Rmannn** [comment]
please check that you re using latest commander version >= 5.1.0

**Comment by Sairyss** [comment]
> 
> 
> please check that you re using latest commander version >= 5.1.0

It is installed in the node_modules/nestjs-console/pachage.json
`"commander": "5.1.0",`
But for some reason is not used.
Had to install it in my root package.json and now it works.

Thanks

**Comment by intpp** [comment]
I have same problem in last version

**Comment by Rmannn** [comment]
@intpp did you try the last solution ? 
You need to update commander npm package to the latest version.
