### ISSUE TITLE
CLI command doesn't work with a request scoped dependency

### ISSUE THREAD

**Issue by tinogo** [Pop-Code/nestjs-console#172]
Hello,

I think, I found a bug with your package and request scoped providers.

We have a CLI command, which is using a request scoped provider as a dependency. Although it doesn't makes much sense to have request scoped providers in CLI contexts (as there are no requests), our motivation is to reuse this service (from a GraphQL- and REST-context, where the request scoping does make sense).

Here is a fully working example to reproduce the problem:
```ts
import { BootstrapConsole } from 'nestjs-console';
import { Injectable, Module, Scope } from '@nestjs/common';
import { Command, Console, ConsoleModule } from 'nestjs-console';

@Injectable({ scope: Scope.REQUEST })
export class MyRequestScopedService {
  public doStuff(): boolean {
    return true;
  }
}

@Console()
export class MyCliService {
  constructor(private readonly myRequestScopedService: MyRequestScopedService) {}

  @Command({
    command: 'foo',
    description: 'A CLI command with a request scoped dependency.',
  })
  public execute(): void {
    console.log(this.myRequestScopedService.doStuff());
    console.log('foo!');
  }
}

@Module({
  imports: [ConsoleModule],
  providers: [MyCliService, MyRequestScopedService],
  exports: [MyCliService],
})
export class MyCliModule {}

const nestConsole = new BootstrapConsole({ module: MyCliModule, useDecorators: true });

nestConsole
  .init()
  .then(async (app) => {
    try {
      await app.init();
      await nestConsole.boot();
      process.exit(0);
    } catch (e) {
      process.exit(1);
    }
  })
  .catch((e) => console.error(e));
```

**Steps to repeat:**
* Run `ts-node console.ts foo`

**Expected result:**
It should print `true` and `foo!`

**Actual result:**
I'm getting the error `Cannot read property 'doStuff' of undefined`.
When you replace `@Injectable({ scope: Scope.REQUEST })` with `@Injectable()`, everything works as it should.

Can you please fix that or are we doing something wrong?

We are currently using NestJS 7.1.2, nestjs-console 3.0.5 (updating it to version 3.0.6 doesn't help) and commander 5.1.0.

**Comment by Rmannn** [comment]
You can't inject scoped service in a non scoped service.
@Injectable({ scope: Scope.REQUEST }) means you r service only exist when a request is created.

**Comment by tinogo** [comment]
Hello @Rmannn,

thank you for your quick reply. :)

Sooo, the only solution for us would be to duplicate the request scoped service to be not request scoped (we can not simply drop the request scoping, as this service holds a request based cache (for the GraphQL- and REST-contexts).

As already said, we are aware that this kind of thing doesn't make much sense for a headless app, but we wanted to reuse the  service to reduce code duplication.

Do you have another solution in mind?

**Comment by tinogo** [comment]
We've came up with a solution. We created a new class decorator, which overrides the default @Injectable() decorator.

```ts
import { Injectable, InjectableOptions, Scope } from '@nestjs/common';
import { basename } from 'path';
export function InjectableCliAware(options?: InjectableOptions): ClassDecorator {
  if (basename(process.argv[1]) === 'console.js' && options?.scope === Scope.REQUEST) {
    options.scope = Scope.DEFAULT;
  }
  return Injectable(options);
}
```

So I think, we can close this issue?! :)

**Comment by Rmannn** [comment]
Nice solution!
