### ISSUE TITLE
[Question]: example use nx project

### ISSUE THREAD

**Issue by tienne** [Pop-Code/nestjs-console#174]
Dear @Rmannn 
Hello
I am very grateful to have this library.
Currently, using Nx, Monorepo Project,
We would like to divide the development into two applications, api Application and Cli Application.

Is there an example of developing this library using nx cli instead of using ts-node?

**Comment by Rmannn** [comment]
Hi, you can have a look on this thread https://github.com/Pop-Code/nestjs-console/issues/142#issuecomment-636024093

**Comment by tienne** [comment]
Thank you. I saw the issue, but I wanted to do it in a development environment, not a product environment.

**Comment by Rmannn** [comment]
You could also have a look on this thread to help https://github.com/nrwl/nx/issues/1230#issuecomment-634455420
As i understand nx will build the api and any project before to test or serve them.

What you want to do is to execute code without building anything. You want to execute things in dev env, and not in a built dev env.
Maybe using ts-node will help you to execute the console.

I really do not like how nx works, but that's my pov. :)

**Comment by tienne** [comment]
Oh! Thanks to you, I know what to do!

I want to ask you a question, from what point of view do you hate nx?
Can you tell me in more detail?

**Comment by Rmannn** [comment]
I don't hate nx. I do not need to have an overlay that will build everything for me. I am enough confident with typescript, node and webpack to manage my own build processes, even for large projects. (No as large as google ones ;) )

I think the dev env should stay pure. More overlay you add, more difficult it will be to learn, understand and masterize each build process. 

Also the documentation is not enough complete.

I think nx is good for large teams and for large projects, where users can take time to overwrite each part of build processes that are required.

The last thing is that i do not want to mix all parts of a projects. 
I use to dev monorepos with lerna to create server parts or shared libraries. And i generally have another monorepo for clients. 
Developers that are working on clients are confident with client code. Others with server code.
I do not want to have all the code of a business network in the same repository.

Hope you will be able to do what you need. Whatever the road you take.
