### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by kashyap-aditya** [Pop-Code/nestjs-console#177]
Have a function "createUser" that takes 2 required parameters and 2 optional parameters. 
Want to be able to specify the command, like so:
`npm run console -- create-user -n adi -e abc@gmail.com  -w 180
`
Tried the following but it didn't work. Please provide some idea about how to create such commands
```
/**
     * Creates a user
     * Required Params: name, email
     * Optional Params: height, weight
     */
    this.consoleService.createCommand(
      {
        command:
          'create-user <name> <email> [height] [weight]',
        description: 'create an organization',
        options: [
          {
            flags: '-n, --name',
            description: 'name of person',
          },
          {
            flags: '-e, --email',
            description:
              'email of person',
          },
          {
            flags: '-h, --height',
            description: 'height of person,
          },
          {
            flags: '-w, --weight',
            description: 'weight of person',
          },
        ],
      },
      DatabaseService.prototype.createUser.bind(this),
      cli, // attach the command to the cli
    );
```

**Comment by Rmannn** [comment]
Using commander you can use arguments and options.
Options must not be specified in the command string, only arguments must be specified in the command string.

Looking the way you want to invoke your function, you should only use options.

So
```ts
this.consoleService.createCommand(
    {
    command: 'create-user',
    description: 'create an organization',
    options: [
        {
        flags: '-n, --name',
        description: 'name of person',
        },
        {
        flags: '-e, --email',
        description:
            'email of person',
        },
        {
        flags: '-h, --height',
        description: 'height of person,
        },
        {
        flags: '-w, --weight',
        description: 'weight of person',
        },
    ],
    },
    DatabaseService.prototype.createUser.bind(this),
    cli, // attach the command to the cli
);
```

In database service createUser method you can get options the following way:

```ts
import * as commander from 'commander';
...
// in your class method
createUser = async (command: commander.Command) => {
    // get all options from command
    const options = command.opts();
    console.log(options.name, options.email, options.height, options.weight);
} 
```

If you use command argument instead options like this `command: 'create-user <arg1> <arg2>',`
You can get arguments from parameters of the binded method.

```ts
import * as commander from 'commander';
...
// in your class method
createUser = async (arg1: any, arg2: any, command: commander.Command) => {
  const options = command.opts();
} 
```

I know that the signature of the command handler must be documented, it's in the scope of the next release.
```ts
async handler(arg1: any, arg2: any, ...argN: any[], command: commander.Command): Promise<any> | any
```

**Comment by kashyap-aditya** [comment]
The problem with both these solutions is that I also call createUser function from other functions and hence I can't modify the argument list of createUser function. I am wondering what a neat workaround would be. I currently made another function "createUserWrapper" that takes command as input, parses it, and calls "createUser". This way, my original createUser is untouched and I can continue calling it from other functions

**Comment by Rmannn** [comment]
This the way to do it, you generally don't call functions without a wrapper, because you need to parse data before to pass it to yojr internal database service.
