### ISSUE TITLE
database connection not found

### ISSUE THREAD

**Issue by mossaabzaroui** [Pop-Code/nestjs-console#195]
The module works correctly if the services do not use the database.
From the moment we use the repository to access to the database, we get the following error message:
Connection "default" was not found.
In my command module imported this line:
TypeOrmModule.forRoot (typeOrmConfig)
or without parameter:
TypeOrmModule.forRoot ()
=> In both cases it doesn't work
Would you know how to use the database via a command ? An example ?
Thank you.

**Comment by Rmannn** [comment]
Could you try this? https://github.com/Pop-Code/nestjs-console/issues/171#issuecomment-647607753

**Comment by mossaabzaroui** [comment]
It doesn't work but finally i resolved the problem like this :
    imports: [
        TypeOrmModule.forRootAsync({
            useFactory: async () => ({
              type: 'mysql' as 'mysql',
              host: process.env.DB_HOST,
              username: process.env.DB_USER,
              password: process.env.DB_PASS,
              database: process.env.DB_NAME,
              entities: [MyEntity],
            }),
          }),
        ConsoleModule,
    ],
