### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: command.exitOverride is not a function     at ConsoleService.createCommand

### ISSUE THREAD

**Issue by milovidov983** [Pop-Code/nestjs-console#235]
Hi I am trying to migrate from the 1.2.0 version to the 4.0.0 and after making all the necessary changes I get this error on startup

**(node:25252) UnhandledPromiseRejectionWarning: TypeError: command.exitOverride is not a function
    at ConsoleService.createCommand**

Please tell me what could be the problem?

**Comment by Rmannn** [comment]
hi, be sure to migrate to the last version of commander. version 6.1.0

**Comment by milovidov983** [comment]
commander. version 6.1.0
