### ISSUE TITLE
Importing REQUEST breaks cli

### ISSUE THREAD

**Issue by kashyap-aditya** [Pop-Code/nestjs-console#251]
Adding` @Inject(REQUEST) private request` to any service leads to the cli commands in that service not being read properly.

```
import { REQUEST } from '@nestjs/core';

@Injectable()
export class CLIService {
  constructor(
    @Inject(REQUEST) private request,
    private readonly consoleService: ConsoleService,
  ) {
    // get the root cli
    const cli = this.consoleService.getCli();
    this.consoleService.createCommand(
      {
        command: 'test-cli',
      },
      CLIService.prototype.testCLIWrapper.bind(this),
      cli,
    );
}
```

test-cli command is not recognized.

If `@Inject(REQUEST) private request` is commented out, then the test command works

**Comment by Rmannn** [comment]
You can't inject a scoped service in a non scoped service. 
The CliService is non scoped.

You can read this to do what you want.
https://github.com/Pop-Code/nestjs-console/issues/172#issuecomment-648152676

**Comment by kashyap-aditya** [comment]
I am not injecting a scoped service.
I am injecting the request object which exists even for default scopes.
https://docs.nestjs.com/fundamentals/injection-scopes#request-provider

**Comment by kashyap-aditya** [comment]
I wouldn't consider this issue closed. It needs a better solution than what is done in #172 . That is not a feasible solution when using service factories to create services on the fly.

**Comment by Rmannn** [comment]
But this is not an issue, this is a conception limit.

The console module is creating a headless application. The request is never existing during the runtime of a cli process.
I guess the Request service is only created when express is used.

The first thing i would check is to create an NestApplication instead of NestApplicationContext.
You can override the BootstrapConsole::create class method to create a NestApplication.

```ts
// custom bootstrap.ts
import { NestFactory } from '@nestjs/core';
import { NestApplicationOptions } from '@nestjs/common';
import { BootstrapConsole, BootstrapConsoleOptions } from 'nestjs-console';
import { ExpressAdapter } from '@nestjs/platform-express';

export interface CustomBootstrapConsoleOptions extends BootstrapConsoleOptions {
    contextOptions?: NestApplicationOptions;
}

export class CustomBootstrapConsole extends BootstrapConsole {
    static createAppContext(options: BootstrapConsoleOptions) {
        return NestFactory.create(options.module, new ExpressAdapter(), options.contextOptions);
    }
}
```

**Comment by kashyap-aditya** [comment]
I will test and report back. Thank you for your help and quick response.

**Comment by kashyap-aditya** [comment]
Still doesn't work. Same error, it still cannot find the command

**Comment by Rmannn** [comment]
So this is what I thought. The request service does not exist outside of a request at runtime.

**Comment by kashyap-aditya** [comment]
I don't think that is the issue.
Microservice and test packages can and do mock requests.
I believe the issue is that the scanner is using .get() instead of .resolve() and hence it is not able to pick up the cli commands for request scoped services
