### ISSUE TITLE
Update commander peerdependencies version

### ISSUE THREAD

**Issue by floross** [Pop-Code/nestjs-console#302]
**Is your feature request related to a problem? Please describe.**
With npm@7 and the new peer dependencies check, and with the new version of commander package we got a npm install error

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @...
npm ERR! Found: commander@7.2.0
npm ERR! node_modules/commander
npm ERR!   commander@"^7.2.0" from @...
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer commander@"^5 || ^6" from nestjs-console@4.0.0
npm ERR! node_modules/nestjs-console
npm ERR!   nestjs-console@"^4.0.0" from @...
npm ERR!   apps/api-backend
```

**Describe the solution you'd like**
A solution would be to allow commander version 7 inside their peerdependencies

**Describe alternatives you've considered**
For now i use `npm i --force` and everything is working

**Comment by Rmannn** [comment]
Thanks for the update.

Latest version of commander 7.2.0 is breaking some functions of the modules. Many tests fail.
I am working to fix it and upgrade the version.
This will result in BREAKING CHANGES, so a new Major version of the module (nestjs-console@5.0.0) will be published next week.

**Comment by Rmannn** [comment]
nestjs-console v5.0.1 is published.
Warning for breaking changes. Check the wiki to know how to upgrade from v4.
