### ISSUE TITLE
Examples doesn't work?

### ISSUE THREAD

**Issue by Zyles** [Pop-Code/nestjs-console#307]
I copy pasted the examples in the docs and they don't seem to work for me.

There is no output:

```
$ npm run console new
> node dist/console.js "new"

$ npm run console new file asdf
> node dist/console.js "new" "file" "asdf"
```

The first example with "list" command only gives error:

```
$ npm run console

> node dist/console.js

The cli does not contain sub command
npm ERR! code ELIFECYCLE
```

And the syntax `async createFile(name: string): void | Promise<void>` does not parse for me in TS.

Have to changed it to:
`async createFile(name: string): Promise<void>`

Is this package outdated or did I forget something?

NestJS 7.6.15

**Comment by Zyles** [comment]
Ah I see what happened here.

I named my service ConsoleService instead of MyService before reading further below that there is a package in nestjs-console that use this name too.

Seems to work now.

**Comment by Rmannn** [comment]
It should work, but using commander version ^6..2.0

Latest version of commander requires some work that is done, but it needs more tests on our side.
Here's the details https://github.com/Pop-Code/nestjs-console/pull/304
