### ISSUE TITLE
Support in nest v8

### ISSUE THREAD

**Issue by ymchun** [Pop-Code/nestjs-console#317]
Currently I am trying out `nest@8.0.0-alpha.4`, the scanner cannot get the service with the `name` property.
It works when I changed the `name` to `token`.

Change
https://github.com/Pop-Code/nestjs-console/blob/5ff85f4c3794a9efedef78283f0ae39b59ae6a17/src/scanner.ts#L55

To
```typescript
const { metatype, token } = p;
```

Change
https://github.com/Pop-Code/nestjs-console/blob/5ff85f4c3794a9efedef78283f0ae39b59ae6a17/src/scanner.ts#L76

To
```typescript
const instance = app.get(token);
```

**Comment by Rmannn** [comment]
I didn't find any documentation to migrate to nest v8. No changelog at the moment in the v8 branch.
I will publish a @next release with changes once we will have more info about de next release of nextjs.

**Comment by kaufmo** [comment]
Guide is now available here: https://docs.nestjs.com/migration-guide

**Comment by Rmannn** [comment]
Nestjs-console@6.0.0 is now supporting nestjs@^8 in version.
