### ISSUE TITLE
Create Spinner

### ISSUE THREAD

**Issue by louis-lau** [Pop-Code/nestjs-console#48]
In the examples you create a spinner like this:
```
const spin = this.consoleService.createSpinner()
```

I've injected the service. However, it errors out:
```
Property 'createSpinner' is a static member of type 'ConsoleService'
```

Is there anything I'm missing here? Thank you 😁

**Comment by Rmannn** [comment]
Hi, exact, the createSpinner is now a static method and the doc should mention it.
Thx for the report.

You can use it like this
```ts
const spin = ConsoleService.createSpinner();
```
or
```ts
const spin = this.consoleService.constructor.createSpinner();
```

**Comment by louis-lau** [comment]
I see, that makes sense. Thank you! Will you change this our should I submit a PR?

P.S. That was quick

**Comment by Rmannn** [comment]
I will change it.
It will be updated in the next commit :)
