### ISSUE TITLE
Process.env issue

### ISSUE THREAD

**Issue by nayan2** [Pop-Code/nestjs-console#640]
In my main module - which is `CLIMODULE`, I am adding `ConfigModule`, which is recommanded by nestJs. But when I am logging process.env inside it.  I am getting. something unexpected. Unbale to unbale why?

The process.env should give me. the project local `.env` file varibales or OS environment varibale. 

My Module ->

```
import { Module, Global } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import { SeedService } from './seed.service';

@Module({
  imports: [
    ConfigModule.forRoot({
        load: [() => {
            console.log(process.env);
            return {}
        }],
        isGlobal: true
    }),
    ConsoleModule
  ],
  providers: [SeedService],
  exports: [SeedService],
})
export class CliModule {}
```

Any, idea how can I get the local 'environment' variables? OR from a local `.env` file.

**Comment by baijii** [comment]
Same here. I'm using `dotenv` for the config. As soon as I try to execute a console script, it errors at the first env variable it does not know.

```ts
// app.module.ts

import * as dotenv from 'dotenv'
import { Global, Module } from '@nestjs/common'
import { ConfigModule } from '@nestjs/config'
import { ConsoleModule } from 'nestjs-console'

dotenv.config()

@Global()
@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    ConsoleModule,
  ],
})
export class AppModule {}

```

**Comment by nayan2** [comment]
Hei, thanks for the reply. But, the issue has been Fixed.

**Comment by Mottoweb** [comment]
to anyone experincing same issue, even when COnfigModule is not using cache, there may be process.env cache, to clear that i used `dotenv.config({ override: true });` and it helped with cache.
