### ISSUE TITLE
Module '"nestjs-console"' has no exported member 'createSpinner'.

### ISSUE THREAD

**Issue by ctsstc** [Pop-Code/nestjs-console#679]
It seems that `nestjs-console` no longer exports `createSpinner`, I'm updating my dependencies and running into this. I'm not sure if this was removed on purpose. I didn't see anything in release notes, but it seems to be gone from the codebase as well now.

There's still some documentation around this it seems here as well:
- https://github.com/Pop-Code/nestjs-console/wiki/Using-decorators

Otherwise the repository doesn't seem to mention it anywhere anymore.

Just wanted to confirm if it's supposed to be gone now, or if it should be there.

**Comment by ctsstc** [comment]
Upon further investigation it looks like it was removed in the major update to NestJS here:
https://github.com/Pop-Code/nestjs-console/commit/c2cd90b05385096950dcfc1369083ebe1422db17#diff-ca5696b367d474e785317cb7a0d9853fef5729387ab8d0fab4c46268c03aae99

It looks like it was just a proxy to Ora, so I'll just include that in my project and use it directly.

**Comment by Rmannn** [comment]
I didn't want to deal with old dependencies in the package. 
That's why Ora was removed. As you said it was just a proxy. 
Note that the last version of Ora is ESM.

https://github.com/Pop-Code/nestjs-console/blob/master/CHANGELOG.md#900---2023-07-15

**Comment by ctsstc** [comment]
I thought I gave my follow up edit to this, but I guess I didn't post it last week. 
It seems Ora has been kept up to date, but give it's ESM caused too much trouble for me.

I went through the pains of trying to integrate the ESM module into the ecosystem of node + jest + ts; I've been here before, and at the end of the day, I cannot spend hours or days like others have tried to get ESM working in their stack with third party dependencies, so I opted out of it and used some console logs instead :RIP:

**Comment by Rmannn** [comment]
You're right, its a real pain. You could try to fallback to the last non ESM version of ORA. "ora": "5.4.1"

**Comment by Enflow-io** [comment]
+1
