### ISSUE TITLE
Unknown createSpinner mention in wiki

### ISSUE THREAD

**Issue by IfnotFr** [Pop-Code/nestjs-console#712]
Hello,

I am starting using [nestjs-console](https://github.com/Pop-Code/nestjs-console) and when I tried to copy and paste [this example](https://github.com/Pop-Code/nestjs-console/wiki/Using-decorators) I got an unknown `createSpinner` in the main import.

Is this example outdated with the `createSpinner` removed from the library ?

Thanks :)

**Comment by Rmannn** [comment]
Sorry the wiki was out to date. 
`createSpinner` was coming from the [npm ora package](https://www.npmjs.com/package/ora). It has been removed.

You can install it and use it in your code as it was described in the example. Do not forget to import it form it's own package.

**Comment by estani** [comment]
@Rmannn Wiki here still out of date: https://github.com/Pop-Code/nestjs-console/wiki/Using-decorators
(still importing createSpinner, even if not used)
