### ISSUE TITLE
Swallowing errors in v1

### ISSUE THREAD

**Issue by jcrben** [Pop-Code/nestjs-console#75]
My project is not open-source and would have to do some work to create a reproduction, but I may get around to that later. But I'm noticing that this sometimes swallows errors. Node version 12.7.0

I'm seeing this:
![image](https://user-images.githubusercontent.com/5614134/72486170-f14eab00-37be-11ea-8a83-ee984efc21dd.png)

I've run into this before and found the error with a debugger, but in this case vscode isn't picking up an exception - it's just restarting constantly. It seems to be related to this ConfigService
![image](https://user-images.githubusercontent.com/5614134/72486233-20651c80-37bf-11ea-8bd0-7a9f139c994e.png). I eventually narrowed down the line where it stops and
after adding a try / catch around https://github.com/nestjs/nest/blob/2d5cd89135a77066870abaf067986cb1c08213ca/packages/core/injector/injector.ts#L213 I saw this:
![image](https://user-images.githubusercontent.com/5614134/72485894-18f14380-37be-11ea-9bbf-7b4cd0eaa7e3.png)

I'm wondering if there's a way to adjust the code for the console without messing with the underlying nestjs code so that these errors are not swallowed.

**Comment by jcrben** [comment]
As far as "undefined" `properties`, I had accidentally placed it in the try / catch - so that's not the error. It's just exiting with exit code 1.

**Comment by Rmannn** [comment]
Startup errors are not thrown by nestjs. 
The console can not display anything cause the logger is disabled by default.

The default exception filter of nestjs will only log the error and exit the process, so you won't see anything. 

You could try to modify the options you pass to the init of the BootstrapConsole to use a logger and adjust log level to display error only.
https://github.com/Pop-Code/nestjs-console/blob/7aaa3861bf7b7d92dc275efab7107695d0385e35/src/bootstrap.ts#L16-L20

This way you could detect startup errors (reading them).

A real solution would be to implement a custom error handler, but this won't work in our case cause custom handler won't work before init.
The second would be to tell nestjs to throw, as you ask in the issue https://github.com/nestjs/nest/issues/3764

I know one case in v1 when errors are not correctly caught. It's when error are thrown inside a command handler that is a promise. This won't be fixed. In v2 errors are emitted from command handler and thrown from the Console service 
https://github.com/Pop-Code/nestjs-console/blob/8a92c3807aea98a7c8aaaef1327fea9d40f4604f/src/service.ts#L100-L102

**Comment by jcrben** [comment]
Logging is all we need for a good developer experience.

So in v1, updating source to change `logger: false` to `logger: ['error', 'warn']` fixes my issue. In v1, it appears that a different value cannot be passed in https://github.com/Pop-Code/nestjs-console/blob/7aaa3861bf7b7d92dc275efab7107695d0385e35/src/bootstrap.ts#L17

Why have the logger default to false, even in v2? https://github.com/Pop-Code/nestjs-console/blob/d2b6061688e6ee2f77e933659b6a3047aaa6a040/src/bootstrap/abstract.ts#L70

**Comment by Rmannn** [comment]
You can override the contextOptions in the init method, passing a custom logger.
https://github.com/Pop-Code/nestjs-console/blob/7aaa3861bf7b7d92dc275efab7107695d0385e35/src/bootstrap.ts#L14

The logger default to false cause you don't want your cli to log startup things. You want the cli to log a response only. 
Maybe we should set it to ['error'] by default.

**Comment by Rmannn** [comment]
Done in v2.0.3
