### ISSUE TITLE
v2 init fails silently and kills the process

### ISSUE THREAD

**Issue by kevzettler** [Pop-Code/nestjs-console#80]
**Describe the bug**
Console silently fails with: 
```error Command failed with exit code 1.```

and kills the process.

**To Reproduce**
entry point looks like:
```
// console.ts - example of entrypoint
import { BootstrapConsole } from 'nestjs-console';
import { ApplicationModule } from './app.module';

const bootstrap = new BootstrapConsole({
  module: ApplicationModule,
  useDecorators: true
});

bootstrap.init().then(async app => {
  try {
    // init your app
    await app.init();
    // boot the cli
    await bootstrap.boot();
    console.log('**********should boot?*********');
    process.exit(0);
  } catch (e) {
    console.log('*******************');
    console.log(e);
  }
});
```

**Expected behavior**
A failure with some kind of error output 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] `Darwin Kevs-MacBook-Pro.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64`
 - Version [e.g. 22]  `nestjs-console@2.0.1`

```
kevs-mbp:svc-social kevzettler$ node -v
v12.13.1
```

**Comment by Rmannn** [comment]
In v2 the logger is muted. 

You can define a custom logger or a log level from the config of the BootstrapConsole
```ts
const bootstrap = new BootstrapConsole({
  module: ApplicationModule,
  useDecorators: true,
  // add context options (options of the application creation)
  contextOptions: {
      logger: 'error' // warning, info etc... or you could implement your own logger
  }
});
```
As discussed here #75, in the next release this will default to "error".

This should occurs only during app init, not really during a command execution. Nest is not throwing error during init, simply log it and exit the process. This is why you have to use a logger to detect it.

**Comment by kevzettler** [comment]
thanks @Rmannn I know have log output and see

```
[Nest] 51724   - 01/22/2020, 8:38:38 AM   [ExceptionHandler] Nest cannot create the module instance. Often, this is because of a circular dependency between modules. Use forwardRef() to avoid it.

(Read more: https://docs.nestjs.com/fundamentals/circular-dependency)
Scope []
```

This error is not thrown when I run `ApplicationModule` the nestjs app in a server mode. Any thoughts on where to look?

**Comment by Rmannn** [comment]
Can you share your code ? Or can you create a repo to reproduce the error ?

**Comment by floross** [comment]
When I run the cli with `2.0.1` my method is called but the helper is showing directly. I do not have problem during the start of my application (works well when nest start) but only with the cli.

```bash
yarn run v1.21.1
$ yarn workspace *** cli insee check
$ ts-node -r tsconfig-paths/register src/console.ts *** ***
⠋ Get all *** from the ***: console.ts *** [options] [command]

Command to update ***

Options:
  -h, --help  output usage information

Commands:
  ***       ***
Done in 20.18s.

```

**Comment by Rmannn** [comment]
Exact, I am working on this bug.

**Comment by floross** [comment]
Any update one the release date ?

**Comment by Rmannn** [comment]
next week
